### PR TITLE
Fix the feedback messages of all commands

### LINKED ISSUE #128: Fix the feedback messages of all commands

### PR DESCRIPTION
**Pull request by nguyendqminh**

### CODE REVIEW

File: src/main/java/trackitnus/logic/commands/contact/AddContactCommand.java [hunk 1]
```diff
@@ -19,13 +19,14 @@
 
     public static final String COMMAND_WORD = "add";
 
-    public static final String MESSAGE_USAGE = "C " + COMMAND_WORD + ": Adds a contact to the address book. "
+    public static final String MESSAGE_USAGE = Contact.TYPE + " " + COMMAND_WORD
+        + ": Adds a contact to the address book. "
```
Comment (UncleGrandpa925) [inline src/main/java/trackitnus/logic/commands/contact/AddContactCommand.java]: Not address book any more, it should be "Add a contact to the app"

File: src/main/java/trackitnus/logic/commands/contact/DeleteContactCommand.java [hunk 2]
```diff
@@ -19,10 +19,10 @@
 
     public static final String COMMAND_WORD = "delete";
 
-    public static final String MESSAGE_USAGE = "C " + COMMAND_WORD
+    public static final String MESSAGE_USAGE = Contact.TYPE + " " + COMMAND_WORD
         + ": Deletes the contact identified by the index number used in the displayed contact list.\n"
```
Comment (UncleGrandpa925) [inline src/main/java/trackitnus/logic/commands/contact/DeleteContactCommand.java]: This should be "displayed on the screen"

**Review by UncleGrandpa925 — CHANGES_REQUESTED** [review]

**Review by UncleGrandpa925 — APPROVED** [review]
