### PR TITLE
Fix bug where invalid format message is shown when invalid index is found

### LINKED ISSUE #213: [PE-D] Wrong error message displayed for edit lesson command
When a correct command format but an invalid INDEX is inputted, the error message indicates that the command format is invalid.

To reproduce:
Edit a lesson and input an invalid INDEX

Expected outcome:
The error message should indicate that the INDEX is invalid.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: successs404/ped#3

### LINKED ISSUE #214: [PE-D] Integer overflow regarding index
When the correct command format and a huge INDEX number is inputted, the error message changes from invalid index to invalid command format.

Expected outcome:
The error message should indicate that the INDEX is invalid.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: successs404/ped#4

### PR DESCRIPTION
**Pull request by nguyendqminh**

### CODE REVIEW

File: src/main/java/trackitnus/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -31,6 +31,8 @@
  */
 public class ParserUtil {
 
+    public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer.";
+    public static final String MESSAGE_NOT_DIGIT_SEQUENCE = "Index is not a valid digit sequence.";
```
Comment (UncleGrandpa925) [inline src/main/java/trackitnus/logic/parser/ParserUtil.java]: can you move all of these messages to commons/core/Messages.java?

**Review by UncleGrandpa925 — CHANGES_REQUESTED** [review]

**Review by UncleGrandpa925 — APPROVED** [review]
