### PR TITLE
Fix bugs in Module & Lesson

### LINKED ISSUE #75: Can edit task, module, lesson without providing any fields for edit

### PR DESCRIPTION
**Pull request by UncleGrandpa925**

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java [hunk 1]
```diff
@@ -33,16 +33,16 @@ public EditModuleCommand parse(String args) throws ParseException {
         Code code;
 
         try {
+            if (argMultimap.getValue(PREFIX_CODE).isEmpty()) {
+                throw new ParseException("");
+            }
```
Comment (simonteozw) [inline src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java]: Should the ParseException be thrown with empty string? No message?

File: src/test/java/seedu/address/logic/parser/lesson/EditLessonCommandParserTest.java [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+public class EditLessonCommandParserTest {
+    private final EditLessonCommandParser parser = new EditLessonCommandParser();
+
+    @Test
+    public void parse_noFieldsProvided_failure() {
+        assertParseFailure(parser, "", String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+            EditLessonCommand.MESSAGE_USAGE));
+
+
+    }
```
Comment (simonteozw) [inline src/test/java/seedu/address/logic/parser/lesson/EditLessonCommandParserTest.java]: Can remove the 2 lines of whitespace here

File: src/test/java/seedu/address/logic/parser/module/EditModuleCommandParserTest.java [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+public class EditModuleCommandParserTest {
+    private final EditModuleCommandParser parser = new EditModuleCommandParser();
+
+    @Test
+    public void parse_noFieldsProvided_failure() {
+        assertParseFailure(parser, "", String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+            EditModuleCommand.MESSAGE_USAGE));
+
+
+    }
```
Comment (simonteozw) [inline src/test/java/seedu/address/logic/parser/module/EditModuleCommandParserTest.java]: Same here

**Review by simonteozw — COMMENTED** [review]
Looks good! Just a few comments/questions

File: src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java (hunk 1 above)
Comment (UncleGrandpa925) [reply src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java]: Actually I wrote the message for this exception already, but then deleted it because the exception caught on the very next line. Should I comment on why I leave that message empty or just write a message in it?

File: src/test/java/seedu/address/logic/parser/lesson/EditLessonCommandParserTest.java (hunk 2 above)
Comment (UncleGrandpa925) [reply src/test/java/seedu/address/logic/parser/lesson/EditLessonCommandParserTest.java]: done!

File: src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java (hunk 1 above)
Comment (simonteozw) [reply src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java]: Hmm maybe write the new message on this line then in the following line you can write catch (ParseException pe) { throw pe }

File: src/test/java/seedu/address/logic/parser/module/EditModuleCommandParserTest.java [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+
+public class EditModuleCommandParserTest {
+    private final EditModuleCommandParser parser = new EditModuleCommandParser();
+
+    @Test
+    public void parse_noFieldsProvided_failure() {
+        assertParseFailure(parser, "", String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+            EditModuleCommand.MESSAGE_USAGE));
+
+
```
Comment (simonteozw) [inline src/test/java/seedu/address/logic/parser/module/EditModuleCommandParserTest.java]: I meant here, lines 17 - 18

File: src/test/java/seedu/address/logic/parser/lesson/EditLessonCommandParserTest.java [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+public class EditLessonCommandParserTest {
+    private final EditLessonCommandParser parser = new EditLessonCommandParser();
+
+    @Test
+    public void parse_noFieldsProvided_failure() {
+        assertParseFailure(parser, "", String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+            EditLessonCommand.MESSAGE_USAGE));
+
+
```
Comment (simonteozw) [inline src/test/java/seedu/address/logic/parser/lesson/EditLessonCommandParserTest.java]: Actually I meant here lines 17-18

**Review by simonteozw — COMMENTED** [review]
Looks good, just a few comments

File: src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java (hunk 1 above)
Comment (UncleGrandpa925) [reply src/main/java/seedu/address/logic/parser/module/EditModuleCommandParser.java:38]: actually that thing is on line 40 already

**Review by simonteozw — APPROVED** [review]
LGTM
